name: Run Cypress Tests

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 5 * * *" # Runs daily at 5 AM UTC (adjust as needed)

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env: # Pull secrets into runtime environment
      CYPRESS_BASE_URL: ${{ secrets.BASE_URL }}
      CYPRESS_user: ${{ secrets.CYPRESS_USER }}
      CYPRESS_pass: ${{ secrets.CYPRESS_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --browser chrome
