name: Run Cypress Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{ secrets.BASE_URL }}
      CYPRESS_user: ${{ secrets.CYPRESS_USER }}
      CYPRESS_pass: ${{ secrets.CYPRESS_PASS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Debug environment
        run: |
          node --version
          npx cypress --version
      - name: Run Cypress tests
        run: npx cypress run --headed --browser chrome --env viewportWidth=1920,viewportHeight=1080
      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
